### ISSUE TITLE
sensor Mebus/433

### ISSUE THREAD

**Issue by OE5DRO** [NorthernMan54/homebridge-acurite-temperature#2]
if you add '-G' parameter in line 53 in sensor.js this and more sensors can be used.
 53: var proc = child_process.spawn('/usr/local/bin/rtl_433', ['-q', '-F', 'json', '-C', 'si', '-G']);

**Comment by NorthernMan54** [comment]
Tks for this tweak.  Let me review it and add it.

Tks very much

**Comment by OE5DRO** [comment]
additionally i changed line 62:
        62:  var device = getDevice(data.channel); to           
        62:  var device = getDevice(data.id);
because most sensors are on same channel but have different IDs.

and it would be nice to change frquency in config.json, it could be done with '-f', '433xxxxxx' in line 53

**Comment by NorthernMan54** [comment]
If you want to combine your tweaks into a pull request, I can merge it.

**Comment by OE5DRO** [comment]
ok i hope i have done it right :) first time

**Comment by NorthernMan54** [comment]
Looked good, fingers crossed.

**Comment by NorthernMan54** [comment]
Pull Request #3 and Version 0.0.8 includes this
