### ISSUE TITLE
how to add 1 decimal place at temperatur?

### ISSUE THREAD

**Issue by OE5DRO** [NorthernMan54/homebridge-acurite-temperature#4]
my sensor is sending me
{"time" : "2019-04-23 16:51:26", "model" : "Ambient Weather F007TH Thermo-Hygrometer", "device" : 234, "channel" : 1, "battery" : "Ok", "temperature_C" : 18.778, "humidity" : 47, "mic" : "CRC"}
temepratur with 3 digital places but homekit shows no decimal places.
is it rounded in the script or is it done by home kit?

**Comment by NorthernMan54** [comment]
The plugin rounds it to 1 decimal point, but homekit then rounds it to .5's.  If you use the Eve app, it displays at one decimal point.

https://github.com/NorthernMan54/homebridge-acurite-temperature/blob/65f5e9584e12d29640d7093aa96426429b060fcf/sensor.js#L158

**Comment by OE5DRO** [comment]
thank you for your fast answer, ill watch out for this eve app

**Comment by OE5DRO** [comment]
eve. is so cool, thanks!

**Comment by NorthernMan54** [comment]
And it will graph the history for you ;-)
